[window]
option_as_alt = "Both"

[env]
TERM = "xterm-256color"

[font]
normal =      { family = "JetBrainsMono Nerd Font", style = "Regular"     }
bold =        { family = "JetBrainsMono Nerd Font", style = "Bold"        }
italic =      { family = "JetBrainsMono Nerd Font", style = "Italic"      }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[general]
live_config_reload = true
import = [
    "./themes/dark_plus.toml",
    "./alacritty.local.toml"
]
