[general]
live_config_reload = true
import = [
    "./themes/dark_plus.toml"
]

[window]
option_as_alt = "Both"

[env]
TERM = "xterm-256color"

[font]
normal =      { family = "Inconsolata", style = "Regular"     }
bold =        { family = "Inconsolata", style = "Bold"        }
italic =      { family = "Inconsolata", style = "Italic"      }
bold_italic = { family = "Inconsolata", style = "Bold Italic" }
size = 14.0
