force_keyboard_focus = true
selection_wrap = true
hide_action_hints = true
theme = "dotfiles"

[providers]
max_results = 256
default = [
  "desktopapplications",
  "websearch",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

[[providers.prefixes]]
prefix = "!"
provider = "menus:screenshots"

[[providers.prefixes]]
prefix = "#"
provider = "menus:illyan"

